// <auto-generated />
using MCMDirect.Areas.Store.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MCMDirect.Migrations
{
    [DbContext(typeof(MCMContext))]
    [Migration("20210403222631_AddUser")]
    partial class AddUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("MCMDirect.Areas.Store.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Chairs"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sofas"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Media Units"
                        });
                });

            modelBuilder.Entity("MCMDirect.Areas.Store.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            Description = "Keeping it honest Herman Miller is a West Michigan-based company founded with a steadfast belief in bringing integrity to design. This extends to the authorship, materials, craftsmanship, and longevity of its furniture, some of which is part of museum collections worldwide.",
                            Image = "herman_miller.png",
                            Name = "Herman Miller"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            Description = "Timeless American modernism Knoll is a design and manufacturing company that has been producing the work of Eero Saarinen, Marcel Breuer, Warren Platner and others since being founded by Hans Knoll and later run by Florence Knoll. More than 40 Knoll products are in the permanent collection at MoMA.",
                            Image = "knoll.png",
                            Name = "Knoll"
                        },
                        new
                        {
                            ManufacturerId = 3,
                            Description = "Authentic modern design “Our name embodies the mission of our company: to make well-designed products easily accessible to design-savvy professionals.” That was the first sentence in the first DWR catalog, which landed in mailboxes July 4, 1999.",
                            Image = "dwr.png",
                            Name = "Design Within Reach"
                        });
                });

            modelBuilder.Entity("MCMDirect.Areas.Store.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Charles and Ray Eames had ideas about making a better world, one in which things were designed to bring greater pleasure to our lives. Their iconic Eames Lounge Chair and Ottoman (1956) began with a desire to create a chair with “the warm, receptive look of a well-used first baseman’s mitt.” The result embodies what it really means to lounge. In continuous production since its introduction, this set is widely considered one of the most significant designs of the 20th century. Combining soft, inviting leather or mohair with the sleek form of molded wood, the Eames Lounge Chair and Ottoman is the culmination of the Eameses’ efforts to create a club chair using the molded plywood technology they pioneered in the ’40s. Even today, each piece is assembled by hand to ensure the highest level of quality and craftsmanship, and you’ll be pleased to discover the set gets even better with use and age. Cushions snap in and can be removed and changed. This is the authentic Eames Lounge Chair and Ottoman by Herman Miller.",
                            Image = "chair.png",
                            ManufacturerId = 1,
                            Name = "Eames Lounge and Ottoman",
                            Price = 8249.9899999999998
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "The Barcelona Couch (1930) by Ludwig Mies van der Rohe continues to endure as an icon of modernism and master craft. It’s upholstered using a single Spinneybeck cowhide and supported by an African mahogany sapele hardwood frame and stainless steel legs. To create the deep, precise tufting, individual panels of leather are cut, hand-welted and hand-tufted. The Barcelona Couch is a registered trademark of Knoll, Inc., this is the authentic Barcelona Couch by Knoll. Made in U.S.A.",
                            Image = "barcelona.png",
                            ManufacturerId = 2,
                            Name = "Barcelona Couch",
                            Price = 10999.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "A customer favorite since its debut, the Line Collection features geometric frames made out of precisely crafted oak or walnut. It's distinguished by its strong horizontal lines that reflect natural landscapes and lend a sense of restfulness and calm. On the Line Media Console (2010), this eye-catching louvered design also serves a purpose, allowing remotes to control devices inside. Its roomy, well-organized interior brings order to electronics, routers, albums, books and anything else that needs a home. Working from his studio in Singapore, designer Nathan Yong designs thoughtful pieces that resonate with a quiet elegance, for which he credits the congestion of city living. “My work is a reflection of my yearning for nature in this concrete jungle,” he says. Made in Malaysia.",
                            Image = "line_console.png",
                            ManufacturerId = 3,
                            Name = "Line Console",
                            Price = 3295.9899999999998
                        });
                });

            modelBuilder.Entity("MCMDirect.Areas.Store.Models.Product", b =>
                {
                    b.HasOne("MCMDirect.Areas.Store.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCMDirect.Areas.Store.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
